using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LINQTest
{
    /*
        CREATE TABLE Student
        (
             ID INT PRIMARY KEY,
             FirstName VARCHAR(50),
             LastName VARCHAR(50),
             Gender VARCHAR(50)
        )
        GO
        -- Insert the required test data
        INSERT INTO Student VALUES (101, 'Steve', 'Smith', 'Male')
        INSERT INTO Student VALUES (102, 'Sara', 'Pound', 'Female')
        INSERT INTO Student VALUES (103, 'Ben', 'Stokes', 'Male')
        INSERT INTO Student VALUES (104, 'Jos', 'Butler', 'Male')
        INSERT INTO Student VALUES (105, 'Pam', 'Semi', 'Female')
        GO
    */
    internal interface IEnumerable_vs_IQueryable
    {

        public class Student
        {
            public int ID { get; set; }
            public string FirstNamee { get; set; }
            public string LastName { get; set; }
            public string Gender { get; set; }
        }

            class Program
        {
            static void Main(string[] args)
            {
                /*
                using (StudentDBContext DBContext = new StudentDBContext())
                {
                    //To See What SQL Generated By Entity Framework
                    DBContext.Database.Log = Console.Write;
                    //Fetch the Top 2 Records from the Students Database table where Gender = Male
                    IEnumerable<Student> listStudents = DBContext.Students.Where(x => x.Gender == "Male");
                    listStudents = listStudents.Take(2);
                    Console.WriteLine("Top 2 Student Where Gender = Male");
                    foreach (var std in listStudents)
                    {
                        Console.WriteLine(std.FirstName + " " + std.LastName);
                    }
                }
                */
                Console.ReadKey();
            }
        }

    }
}
